//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dblayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPasswordRecoveryTable
    {
        public int UserPasswordRecoveryID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string RecoveryCode { get; set; }
        public Nullable<System.DateTime> RecoveryCodeExpiryDateTime { get; set; }
        public Nullable<byte> RecoveryStatus { get; set; }
        public string OldPassword { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
